In [1]:
import numpy as np
n = np.arrange(27)

AttributeError: module 'numpy' has no attribute 'arrange'

In [2]:
n

NameError: name 'n' is not defined

In [8]:
import numpy as np
n = np.arange(27)

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
type(n)

numpy.ndarray

In [6]:
n = np.arange(3,5)
n

array([3, 4])

In [9]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
n.reshape(3,9)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [12]:
n.reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
import opencv


ModuleNotFoundError: No module named 'opencv'

In [14]:
import cv2


In [17]:
im_g = cv2.imread("smallgray.png", 1)
im_g

array([[[195, 195, 195],
        [127, 127, 127],
        [166, 166, 166]],

       [[127, 127, 127],
        [127, 127, 127],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [255, 255, 255],
        [195, 195, 195]],

       [[127, 127, 127],
        [255, 255, 255],
        [ 71,  71,  71]],

       [[195, 195, 195],
        [255, 255, 255],
        [ 71,  71,  71]]], dtype=uint8)

In [18]:
im_g1 = cv2.imread("smallgray.png", 0)
im_g1

array([[195, 127, 166],
       [127, 127,   0],
       [  0, 255, 195],
       [127, 255,  71],
       [195, 255,  71]], dtype=uint8)

In [19]:
print(im_g)

[[[195 195 195]
  [127 127 127]
  [166 166 166]]

 [[127 127 127]
  [127 127 127]
  [  0   0   0]]

 [[  0   0   0]
  [255 255 255]
  [195 195 195]]

 [[127 127 127]
  [255 255 255]
  [ 71  71  71]]

 [[195 195 195]
  [255 255 255]
  [ 71  71  71]]]
